---
title: "CSCI E-106 : Fall 2025 Midterm Exam"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Instructions

1-) As always, you are required to follow Harvard University academic integrity and honor code.

2-) Open book and open notes exam ( textbooks (print or pdf), lecture slides, notes, practice exam, homework solutions, and TA slides, including all Rmd's*).

3-) You are allowed to use RStudio Desktop or RStudio Cloud (https://rstudio.cloud.) , Microsoft Word, Power Point and PDF reader, and canvas on your laptop.

4-) Proctorio is required to start this exam. If you are prompted for an access code, you must Install and Configure Proctorio on your machine.  

5-) Review the Proctorio Support for Test Takers page, Online Exam Checklist and Proctorio Checklist to help you avoid common errors and who to contact if you run into any issues. 

6-) Practice Setup Quiz is available under Quizzes to test your connection and to find out if you are ok with the Proctorio.

7-) Please read the list of recording and restrictions provided by Proctorio carefully before taking the exam.

8-) The midterm exam will be available from Friday, October 31st at 12 pm ET (U.S. Eastern Time) through Wednesday November 5th at 12:00 pm ET. You must submit your midterm by Wednesday November 5th at 12:00 pm ET. 

9-) Once you start the exam, you must complete the exam in 3 hours or by Wednesday November 5th at 12:00 pm ET.

10-) In order to receive full credit, please provide full explanations and calculations for each questions.

11-) Make sure that you are familiar with the procedures for troubleshooting exam issues. Preview the document and follow the protocol if there are any issues!

12-) Make sure you submit both .Rmd and (knitted) pdf or html files.

13-) You need to have a camera on your laptop.

14-) Please reach out to DCE Online Support by using the information below\newline
DCE Online Support\newline
(617) 998-8571\newline
(Mon-Thurs 10am-11pm, Fri-Sun 10am-8pm EST)\newline
AcademicTechnology@dce.harvard.edu

15-) Our emails:\newline
hakangogtas@yahoo.com\newline
rafael_gomeztagle@g.harvard.edu\newline
andreahatch10@gmail.com\newline
sezer@yahoo.com\newline
iankelk@gmail.com\newline
\newpage

## Problem 1

Refer to the Hitters data set. Major League Baseball Data from the 1986 and 1987 seasons. The data set can be downloaded from the attached CSV file or directly from ISLR2 library in R by copying and pasting the following command into R console:library(ISLR2);data("Hitters").  (85 Points)

Description of the data is below and there  are 322 observations and 20 variables, including 3 categorical variables (League, Division and NewLeague).

AtBat=Number of times at bat in 1986\newline

Hits=Number of hits in 1986\newline

HmRun=Number of home runs in 1986\newline

Runs=Number of runs in 1986\newline

RBI=Number of runs batted in in 1986\newline

Walks=Number of walks in 1986\newline

Years=Number of years in the major leagues\newline

CAtBat=Number of times at bat during his career\newline

CHits=Number of hits during his career\newline

CHmRun=Number of home runs during his career\newline

CRuns=Number of runs during his career\newline

CRBI=Number of runs batted in during his career\newline

CWalks=Number of walks during his career\newline

League=A factor with levels A and N indicating player's league at the end of 1986\newline

Division=A factor with levels E and W indicating player's division at the end of 1986\newline

PutOuts=Number of put outs in 1986\newline

Assists=Number of assists in 1986\newline

Errors=Number of errors in 1986\newline

Salary=1987 annual salary on opening day in thousands of dollars\newline

NewLeague=A factor with levels A and N indicating player's league at the beginning of 1987\newline 


a- ) Remove the missing data by using na.omit command (e.g. Hitters<-na.omit(Hitters)). Create dummy variables for the categorical variables League, Division and NewLeague. Drop the categorical variables after creating the dummy variables from the data set. Perform initial data analyses to identify outliers, and variables that show high correlation with the salary and with each other. Please discuss your findings. (15 points)

b- ) Create train and test data sets: select a random sample of 70% observations from the data set for the train data set and remaining  cases for the test data set. (use set.seed(1299) before selecting the sample) (5 points)

**Use train data set to answer questions part c to f below**

c- ) Build a regression model to predict salary by using all the variables. Check all regression model assumptions visually with appropriate graphs and conduct the Breusch-Pagan Test to determine if the error variances are constant. Evaluate the model performance on the training data set. Please discuss your findings (10 points).


d- ) Use stepwise (both ways) model selection to select the best model for predicting the Salary on the train data set. **Ensure that all variables are significant, use ** $\alpha=0.05$. Justify your choice of model. Check all regression model assumptions visually with appropriate graphs and conduct the Breusch-Pagan Test to determine whether or not the error variances are constant. Evaluate the performance of regression model on the train data set. Please discuss your findings (15 points) 

e- ) Build a lasso regression model to predict Salary by using all variables and compare the model performance against your model on part d.(15 points)

f- ) Build a robust regression model by using the same model in part d and comment on your findings. (10 points)

**Use test data set to answer the question below**

g- ) Compare the performance of models built in part d, e, and f. Which model would you choose and why? (15 points)


## Problem 2

Use the train and test data you developed on the first question. Answer the following questions. (15 Points)

a-) Perform Box-Cox transformation to decide if Salary variable should be transformed by using all variables on the train data set. If indicated, transform the Salary variable and refit your regression model on the train data set. Check all regression model assumptions visually with appropriate graphs and conduct the Breusch-Pagan Test to determine whether or not the error variances are constant. Please discuss your findings. (10 points)

b-) Evaluate the model you built on the transformed Salary performance on the test data set. Please discuss your findings. (5 points)
