---
title: 'CSCI E-106:Assignment 5'
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(lmtest))
suppressPackageStartupMessages(library(faraway))
library(MASS)
library(car)
set.seed(1023)
```

### Brian Ledger

## Problem 1 

\textbf{Refer to the CDI data set. The number of active physicians (Y) is to be regressed against total population , total personal income, land area and geographic region  ("Geographic region classification is that used by the U.S. Bureau of the Census, where: 1 = NE, 2 = NC, S = 3, W=4")}

```{R}
cdi_data = read.csv("CDI Data.csv")[,c(
  "Number.of.active.physicians",
  "Total.population",
  "Total.personal.income",
  "Land.area",
  "Geographic.region"
  )]
tail(cdi_data)
```

a-) \textbf{Create Dummy variables for Geographic Region.}

```{R}
cdi_data$Geographic.region = factor(
  cdi_data$Geographic.region,
  c(2,3,4,1),
  c(".NC", ".S", ".W", ".NE"),
  )
```

b-) \textbf{Fit a regression model by using all variables above.}

We'll make regressions with and without geographic region.
```{R}
summary(lm(Number.of.active.physicians ~ . -Geographic.region, cdi_data))
```

```{R}
cdi_lm = lm(Number.of.active.physicians ~ ., cdi_data)
summary(cdi_lm)
```

\textbf{Comment on your model.}

The coefficients of determination are more or less equal.

None of the geographic region have a significant p-value (at $\alpha=0.5$). We
would assess that there is no relationship between geographic region and number 
of active physicians.

The intercept doesn't have a significant p-value. We would assess that the
number of active physicians wouldn't be significantly different from zero if all
variables were zero. This scenario is non-sense in the context of land area,
population, etc.

c-) \textbf{Test whether any geographic effects are present; use $\alpha$ = .10.}

None of the geographic areas regress with a p-value less than $\alpha$ = .10.

\textbf{State the alternatives, decision rule, and conclusion.}

The null hypothesis is that the geographic region has no effect on number of
active physicians.

The alternative hypothesis is that the geographic region has an effect on the
number of active physicians.

```{R}
alpha = 0.1
df = nrow(cdi_data)-7
t_critical = qt(1-alpha, df)
p_critical = pt(t_critical, df)
```

The critical T-value is `r round(t_critical, 3)`. If the T-value of any factor
is greater than the critical T-value, it would be significant.

Because all of the T-values of the geographic regions are less than the 
critical T-value, we do not discharge the null hypothesis. We assess that the
geographic region has no effect on the number of active physicians.

\textbf{What is the P-value of the test?}

The critical P-value of the test is `r p_critical`.

d-) \textbf{Check the constant variance assumption for the errors.}

The null hypothesis of the Brown Forsythe test is that the variances of all 
of the groups of residuals are equal.

The alternative hypothesis is that the variances of residuals differ between
groups.

```{R}
leveneTest(cdi_lm$residuals, cdi_lm$model$Geographic.region, center=median)
```

The critical F-value is `r pf(0.95,3,436)`. We cannot discharge the null
hypothesis. We assess that the variances of all of the groups of residuals are 
equal.

e-) \textbf{Check the normality assumption.}

```{R}
plot(cdi_lm, which=2)
```

The Q-Q plot shows significant deviation at the ends of the residuals.

```{R}
shapiro.test(cdi_lm$residuals)
```

The Shapiro test indicates that the residuals are not normally distributed.

f-) \textbf{Check for large leverage points.}

The hat matrix of a linear regression is defined by:

$$
\hat{H} = X(X^TX)^{-1}X^T
$$

The hat matrix is a symmetric, idempotent, projection matrix that takes observed
responses to the fitted values of a lienar regression. The hat matrix is unique
when the design matrix is non-singular.

The diagonal elements of the hat matrix are called the leverage-scores.

The sum of the leverage scores is the sum of the diagonal elements.The sum of 
diagonal elements of a matrix is called the trace. In the context of
symmetric, idempotent matrices, the trace is equal to the rank of the matrix.
Thus, when the design matrix is non-singular (full rank), the sum of the 
leverage scores is the same as the degrees of freedom in the design matrix.

The mean leverage score is $\frac{df}{N}$. Leverage scores can range from
$\frac{1}{N}$ to 1. Scores of $\frac{1}{N}$ are constituted by points that lie
on the mean, and therefore have no leverage, and no influence. Scores that 
approach 1 are constituted by increasingly extreme outliers, with high leverage,
but not necessarily high influence.

One convention for identifying points of high leverage is to observe points in
excess of 2 or 3 times the mean leverage score.



```{R}
N = nrow(cdi_data)
cdi_df = attributes(logLik(cdi_lm))$df
cdi_mean_ls = cdi_df/N
cdi_hvs = hatvalues(cdi_lm)
cdi_hl_indices = which(cdi_hvs > 3*cdi_mean_ls)
```

There are `r nrow(cdi_hl_indices)` points in excess of 3 times the mean
leverage score.

```{R}
for (factor in c("Total.personal.income", "Total.population", "Land.area")) {
  factor_hum = chartr(".", " ", factor)
  plot(
    cdi_data[,factor], 
    cdi_data$Number.of.active.physicians, 
    main=paste("Physicians", factor_hum, sep=" vs "),
    xlab=factor_hum,
    ylab="Number of active physicians",
    pch = 19, 
    cex=0.25
  )
  abline(cdi_lm$coefficients["(Intercept)"], cdi_lm$coefficients[factor])
  points(
    cdi_data[cdi_hl_indices, factor], 
    cdi_data[cdi_hl_indices, "Number.of.active.physicians"], 
    col="blue"
  )
}
```

g-) \textbf{Check for outliers.}

```{R}
cdi_lm_residual_mean = mean(cdi_lm$residuals)
cdi_outlier_crit = 3*sd(cdi_lm$residuals)
cdi_outlier_hi = cdi_lm_residual_mean + cdi_outlier_crit
cdi_outlier_lo = cdi_lm_residual_mean - cdi_outlier_crit
cdi_outlier_idxs = which(cdi_lm$residuals > cdi_outlier_hi | cdi_lm$residuals < cdi_outlier_lo)

cdi_outliers = cdi_data[cdi_outlier_idxs,]
cdi_outlier_residuals = cdi_lm$residuals[cdi_outlier_idxs]
plot(
  cdi_outliers$Number.of.active.physicians,
  cdi_outlier_residuals,
  main = "CDI Linear Regression Residual Outliers",
  xlab = "# Active Physicians",
  ylab = "|y_0-y|",
)
abline(cdi_outlier_hi, 0)
abline(cdi_outlier_lo, 0)
```

h-) \textbf{Check for influential points.}

DFFITS, short for difference of fits, is a measure of influence. The definition
of DFFITS for a point at index $i$ is given by

$$
DFFITS_i = \frac{\hat{y}_i - \hat{y}_{(i)}}{\sqrt{MSE_{(i)}h_{ii}}}
$$
In this formula, $\hat{y}_i$ is the value of the predictor at $i$; $h_{ii}$ is 
the $i$th leverage value; $\hat{y}_{(i)}$ and $MSE_{(i)}$ are, respectively, the
prediction and mean-squared error at $i$ for the subsample that omits the $i$th
observation.

One convention for identifying points of high influence is to compare their
DFFITS values to the following:

$$
\sqrt{\frac{df_{(i)}}{N-df_{(i)}}}
$$

where $df_{(i)}$ is the degrees of freedom of the subsample, i.e. $df-1$.

```{R}
cdi_dffits = dffits(cdi_lm)
cdi_dffits_crit = sqrt((df-1)/N)
cdi_dffits_hi = which(cdi_dffits > cdi_dffits_crit)
print(cdi_data[cdi_dffits_hi,])
```

```{R}
for (factor in c("Total.personal.income", "Total.population", "Land.area")) {
  factor_hum = chartr(".", " ", factor)
  plot(
    cdi_data[,factor], 
    cdi_data$Number.of.active.physicians, 
    main=paste("Physicians", factor_hum, sep=" vs "),
    xlab=factor_hum,
    ylab="Number of active physicians",
    pch = 19, 
    cex=0.25
  )
  abline(cdi_lm$coefficients["(Intercept)"], cdi_lm$coefficients[factor])
  points(
    cdi_data[cdi_hl_indices, factor], 
    cdi_data[cdi_hl_indices, "Number.of.active.physicians"], 
    col="blue"
  )
  points(
    cdi_data[cdi_dffits_hi, factor], 
    cdi_data[cdi_dffits_hi, "Number.of.active.physicians"], 
    col="red"
  )
}
```


## Problem 2

```{R}
data(prostate,package="faraway")
p_data = prostate; rm(prostate)
tail(p_data)
```

\textbf{Use lpsa as the response and the other variables as predictors to answer
the questions below.}

a-) \textbf{Create train and test data sets. Use 70% of the data for train data 
set and use remaining data (30% of data). For test data set 
(use set.seed(1023)).}

```{R}
popN = nrow(p_data)
alphaN =round(7/10*popN)
idx_train = sample(popN, size = alphaN, replace=FALSE)
train = p_data[idx_train,]
trainN = nrow(train)
test = p_data[-idx_train,]
testN = nrow(test)
print(paste(trainN, popN, sep="/"))
```

\textbf{Build a regression model to predict lpsa on the train data set.} 

```{R}
p_lm = lm(lpsa ~ ., p_data)
```

\textbf{Write down the regression model and comment on the model performance.}

```{R}
p_lm_summary = summary(p_lm)
print(p_lm_summary)
```

The factors `age`, `lbph`, `lcp`, `gleason`, and `pgg45` have low significance.
The Adjusted R-squared of 0.6234 might be improved by dropping these variables.

b-) \textbf{Visually by using the graphs, comment on regression model 
assumptions.}

```{R}
par(mfrow=c(1,2))
plot(p_lm)
```

The Q-Q residuals deviate near the ends. The standardized residuals don't exceed
2 SD. There are no points in excess of 0.5 Cook's distance.

c-) \textbf{Test the model performance on the test data and comment of model 
stability and performance.}

```{R}

predictTest <-predict(p_lm, test)
modelTest <- cbind(predictTest, test)
testResiduals = modelTest$lpsa - modelTest$predictTest
dimE = testN - p_lm$rank

sst = sum((modelTest$lpsa-mean(modelTest$lpsa))^2)
sse = sum(testResiduals^2)
ssr = sum((modelTest$predictTest - mean(modelTest$lpsa))^2)

mse = sse/dimE
rse = sqrt(mse)
rmse = sqrt(sse/length(testResiduals))
rSquared = 1.0 - (sse/sst)
mae = sum(testResiduals)/length(testResiduals)

model_summary = data.frame(MSE=c(mse), RSE=rse, RMSE=c(rmse), 
                           Rsquared=c(rSquared), MAE=c(mae))
print(model_summary)
```
The training and test R-squared vales are 0.6548 and 0.6600 respectively. The
model performs similarly on the training and test data, so it might not be
overfitted.

d-) \textbf{Perform Breusch-Pagan Test, write down null and alternative 
hypotheses and your conclusion.}

$H_0$: The error variances in the regression residuals are homoscedastic.

$H_a$: The error variances in the regression residuals are heteroscedastic.

```{R}
bptest(p_lm)
```

In the linear model, the p-value is large, so we do not discharge the null
hypothesis. We assess that the error variances in the regression residuals are
homoscedastic.

e-) \textbf{Use the Box–Cox method to determine the best transformation on the 
response. if transformation is needed, perform the transformation and rebuild 
the model on the train data and check the model stability on the test data set.}

`lpsa` likely means log-prostate specific antigen. The log values run into the
negatives, so Box-Cox can't be applied directly.

It's possible that Box-Cox was run on the raw psa data, and a value of 
`\lambda=0` supported taking the log of the psa data. Let's test this.

```{R}
p_lm_with_psa = update(p_lm, exp(lpsa) ~ .)
p_bc = MASS::boxcox(p_lm_with_psa, plotit=TRUE)
lambda_bc = p_bc$x[which.max(p_bc$y)]
```
The value of lambda is `r lambda_bc`. This supports our hypothesis.

## Problem 3

### Commercial properties data set. 

\textbf{A commercial real estate company evaluates vacancy rates, square 
footage, rental rates, and operating expenses for commercial properties in a 
large metropolitan area in order to provide clients with quantitative 
information upon which to make rental decisions. The data are taken from 81 
suburban commercial properties include the age (X1), operating expenses and 
taxes (X2), vacancy rates (X3), total square footage (X4), and rental rates 
(Y).}

a-) \textbf{Fit regression model for four predictor variables to the data.}

Let's look at a sample of the data.

```{R}
cpds_data = read.csv("Commercial Properties Data Set.csv")
names(cpds_data) =c("Rate", "Age", "Costs", "Vacancy", "Size")
tail(cpds_data)
cpds_lm = lm(Rate ~ ., cpds_data)
summary(cpds_lm)
```

\textbf{State the estimated regression function.}

This multilinear regression has four factors: Age, Costs, Vacancy, and Size. 
Generally:

$$
Rate = \beta_0 + \beta_1Age + \beta_2Costs + \beta_3Vacancy + \beta_4Size + \varepsilon
$$

Given this model, over this data-set, we observe that $\beta_3$ is not 
significantly different from 0. Dropping vacancy from the model gives a 
marginally higher Adjusted R^2 (0.5667  vs 0.5629).


b-) \textbf{Visually using the appropriate graphs, comment on the regression 
model assumptions.}

The assumptions are:
\begin{itemize}
\item Observations are independent and identically distributed.
\item variance is homescedastic.
\end{itemize}
```{R}
pairs(
  main = "check i.i.d.",
  cpds_data[,c("Age", "Costs", "Vacancy", "Size")])
```

Factors Size and Cost appear to move together.  

```{R}
standardized_residuals = cpds_lm$residuals/sd(cpds_lm$residuals)
plot(standardized_residuals, main="Standardized Residuals")
```

The residuals appear to be normally distributed. I assess that the variance
is homescedastic.

The standardized residuals hardly exceed 2 standard deviations. 


c-) \textbf{Divide the 81 cases into two groups. placing the 40 cases with the 
smallest fitted values into group 1 and the remaining cases into group 2. 
Conduct the Brown-Forsythe test.}

The null hypothesis of the Brown Forsythe test is that the variances of
of the two groups of fitted values are equal.

The alternative hypothesis is that the variances differ between the two
groups of fitted values.

```{R}
cpds_data_split = cpds_data
split = factor(cpds_lm$fitted.values < median(cpds_lm$fitted.values))
leveneTest(cpds_lm$fitted.values, split, center=median)
```

The p-value for the Brown Forsythe test is 0.2051. Because it is much larger 
than 0.05 we cannot discharge the null hypothesis. We assess that the 
variances of the two groups of fitted values are equal.

d-) \textbf{Fit a second order model} ($Y = b_0 + b_1 X_1 +b_2 X_2 + b_3 X_3+b_4X_4+b_5X_{1}^{2}+b_6X_{2}^{2}+b_7X_{3}^{2}+b_8X_{4}^{2}+b_9X_{1}X_{2}+ b_{10}X_{1}X_{3}+b_{11}X_{1}X_{4}+b_{12}X_{2}X_{3}+b_{13}X_{2}X_{4}+
b_{14}X_{3}X_{4}+b_{15}X_{1}X_{2}X_{3}+b_{16}X_{1}X_{2}X_{4}+
b_{17}X_{2}X_{3}X_{4}+b_{18}X_{1}X_{2}X_{3}X_{4}+b_{19}X_{1}X_{3}X_{4}$)

```{R}
cpds_full_fit = lm(Rate ~ Age + Costs + Vacancy + Size + Age:Age + Costs:Costs + Vacancy:Vacancy + Size:Size + Age:Costs + Age:Vacancy + Age:Size + Costs:Vacancy + Costs:Size + Vacancy:Size + Age:Costs:Vacancy + Age:Costs:Size + Costs:Vacancy:Size + Age:Costs:Vacancy:Size + Age:Vacancy:Size, data=cpds_data)
```

\textbf{Drop the insignificant variables from the model one at a time, refit the 
model and repeat this until all the variables you have in the model are 
significant.}

```{R}
trim_model = function(model, significance_level, runs=1) {
  model_summary = summary(model)
  high_ps = model_summary$coefficients[-1,"Pr(>|t|)"] > significance_level
  while (any(high_ps)) {
    highest_p = max(high_ps)
    highest_p_factor = names(high_ps[high_ps == highest_p])[1]
    change_formula_str = paste(". ~ . - ", highest_p_factor)
    model = update(model, as.formula(change_formula_str))
    model_summary = summary(model)
    high_ps = model_summary$coefficients[-1,"Pr(>|t|)"] > significance_level
  }
  model
}

summary(trim_model(cpds_full_fit, significance_level = 0.05))
summary(trim_model(cpds_full_fit, significance_level = 0.01))
```

\textbf{Compare this again the model in part b)}

When we trim to a 0.05 significance level, Adjusted R-Squared increases, from 
0.5629 to 0.6779. When we trim to a 0.01 significance level, Adjusted R-Squared
decreases to 0.4893.

The new models are significantly smaller. They are easier to comprehend.

Reducing an expanded basis in this way effectively transforms the data to a form
where non-trivial relationships between the factors are accounted for, and
multi-collinearity is reduced.